// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ddr_project;



/************************************************************/
/**
 * 
 */
public class blue_decorator extends DECORATOR{
	/**
	 * 
	 */
	public blue_decorator(SHAPE_FACTORY shape_to_decorate) {
		super(shape_to_decorate);
	}
	
	public void DRAW() {
		set_blue_color();
	}
	/**
	 * 
	 */
	public void set_blue_color() {
		System.out.println("blue color filled in");
	}
};
