// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ddr_project;



/************************************************************/
/**
 * 
 */
public class circle implements SHAPE_FACTORY
 {
	/**
	 * 
	 */
	public void DRAW() {
		System.out.println("CIRCLE OBJECT CREATED");
	}
	public String get_type() {
		return "circle";
	}
};
