// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ddr_project;



/************************************************************/
/**
 * 
 */
public class CONNECTOR {
				/**
				 * 
				 */
	public SHAPE_FACTORY shape;
				/**
				 * 
				 */
	public DIMENSION_STRATEGY movement_of_shape;
	/**
	 * 
	 */
	public SHAPE_FACTORY get_shape(String type) {
		if(type.equals("circle")) {
			shape = new circle();
			return shape;
		}else {
			shape = new rectangle();
			return shape;
		}
		
	}
	/**
	 * 
	 */
	public void set_strategy(DIMENSION_STRATEGY ds) {
		this.movement_of_shape = ds;
	}
	public void execute_strategy(String type) {
		this.movement_of_shape.MOVEMENT(type);
	}
	/**
	 * 
	 */
	public void get_docaration(String type,SHAPE_FACTORY shape_parameter) {
		if(type=="red_decoration") {
			shape_parameter = new red_decorator(this.shape);
			shape_parameter.DRAW();
		}
		else if(type=="blue_decoration") {
			shape_parameter = new blue_decorator(this.shape);
			shape_parameter.DRAW();
		}
	}
};