// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ddr_project;



/************************************************************/
/**
 * 
 */
public class DEMO {
	/**
	 * 
	 */
	public static void main(String args[]) {
		
		SHAPE_FACTORY s1;
		CONNECTOR c1 = new CONNECTOR();
		
		s1 = c1.get_shape("circle");
		s1.DRAW();
		
		c1.set_strategy(new twoD_shape());
		c1.execute_strategy("circle");
		
		c1.get_docaration("red_decoration",s1);
		
		System.out.println("\n");
		
		SHAPE_FACTORY s2;
		CONNECTOR c2 = new CONNECTOR();
		
		s2 = c2.get_shape("rectangle");
		s2.DRAW();
		
		c2.set_strategy(new threeD_Shape());
		c2.execute_strategy("rectangle");
		
		c2.get_docaration("blue_decoration",s2);
		
	}
};
