// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ddr_project;



/************************************************************/
/**
 * 
 */
public interface DIMENSION_STRATEGY {
	/**
	 * 
	 */
	
	public void MOVEMENT(String type) ;
};
