// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ddr_project;



/************************************************************/
/**
 * 
 */
public class rectangle implements SHAPE_FACTORY
 {
	/**
	 * 
	 */
	public void DRAW() {
		System.out.println("rectangle drawn");
	}
	public String get_type() {
		return "rectangle";
	}
	/**
	 * 
	 */
};
