// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ddr_project;



/************************************************************/
/**
 * 
 */
public class red_decorator extends DECORATOR{
	/**
	 * 
	 */
	public red_decorator(SHAPE_FACTORY shape_to_decorate) {
		super(shape_to_decorate);
	}
	
	public void DRAW() {
		set_red_color();
	}
	/**
	 * 
	 */
	public void set_red_color() {
		System.out.println("red color filled in");
	}
};
