// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ddr_project;



/************************************************************/
/**
 * 
 */
public class threeD_Shape implements DIMENSION_STRATEGY
 {
	/**
	 * 
	 */
	public void MOVEMENT(String type) {
		System.out.println(type + " shape is moving in 3d");
	}
	/**
	 * 
	 */
};
