// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ddr_project;



/************************************************************/
/**
 * 
 */
public class twoD_shape implements DIMENSION_STRATEGY
 {
	/**
	 * 
	 */
	public void MOVEMENT(String type) {
		System.out.println(type + " is moving in 2D");
	}
	/**
	 * 
	 */
};
